[package]
name = "aardvark-dns"
version = "0.1.0"
edition = "2018"
authors = ["github.com/containers"]
description = "A container-focused DNS server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.4"
env_logger = "0.9.0"
log = "0.4.14"
